[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
payobvio_solana_program = "FB7QEze2Xmxiw4oh1SfM2WyCwEgAY6oY27dbLPQ365HT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
